# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6d3e4bbbee6b055229ee2e9992d73249e0ffbb65d3609461a7f996c7f4eca5aad2cb4323082b66ea12b09bed65501447ab296aecb32260c8ee7596b91ae5c0b

test:
  secret_key_base: 4fb0f9125010ba81e0b967fe05d24bcf639535ca4813f390f9047c6fe35eac86716912c19ab1d6aa70dd614907979b8411d7c9d61d317ee9b2eb0c3cfc0d2684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
